
package com.ls.soa.game.fantasy.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "CategoryDictionaryService", targetNamespace = "http://soap.service.fantasy.game.soa.ls.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface CategoryDictionaryService {


    /**
     * @param arg1
     * @param arg0
     * @return returns com.ls.soa.game.fantasy.service.soap.CategoryDictionaryDTO
     * @throws InvalidTokenException_Exception
     * @throws InsufficientPermissionsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://soap.service.fantasy.game.soa.ls.com/", className = "com.ls.soa.game.fantasy.service.soap.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://soap.service.fantasy.game.soa.ls.com/", className = "com.ls.soa.game.fantasy.service.soap.CreateResponse")
    public CategoryDictionaryDTO create(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    CategoryDictionaryDTO arg1)
            throws InsufficientPermissionsException_Exception, InvalidTokenException_Exception
    ;

}
