
package com.ls.soa.game.fantasy.service.soap;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ElementServiceImplService", targetNamespace = "http://soap.service.fantasy.game.soa.ls.com/", wsdlLocation = "http://localhost:8080/soap-service/ElementService?wsdl")
public class ElementServiceImplService
        extends Service {

    private final static URL ELEMENTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ELEMENTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ELEMENTSERVICEIMPLSERVICE_QNAME = new QName("http://soap.service.fantasy.game.soa.ls.com/", "ElementServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soap-service/ElementService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ELEMENTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ELEMENTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ElementServiceImplService() {
        super(__getWsdlLocation(), ELEMENTSERVICEIMPLSERVICE_QNAME);
    }

    public ElementServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ELEMENTSERVICEIMPLSERVICE_QNAME, features);
    }

    public ElementServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ELEMENTSERVICEIMPLSERVICE_QNAME);
    }

    public ElementServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ELEMENTSERVICEIMPLSERVICE_QNAME, features);
    }

    public ElementServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ElementServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns ElementService
     */
    @WebEndpoint(name = "ElementServiceImplPort")
    public ElementService getElementServiceImplPort() {
        return super.getPort(new QName("http://soap.service.fantasy.game.soa.ls.com/", "ElementServiceImplPort"), ElementService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ElementService
     */
    @WebEndpoint(name = "ElementServiceImplPort")
    public ElementService getElementServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.service.fantasy.game.soa.ls.com/", "ElementServiceImplPort"), ElementService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ELEMENTSERVICEIMPLSERVICE_EXCEPTION != null) {
            throw ELEMENTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ELEMENTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
