
package com.ls.soa.game.fantasy.service.soap;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "AuthServiceImplService", targetNamespace = "http://soap.service.fantasy.game.soa.ls.com/", wsdlLocation = "http://localhost:8080/soap-service/AuthService?wsdl")
public class AuthServiceImplService
        extends Service {

    private final static URL AUTHSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName AUTHSERVICEIMPLSERVICE_QNAME = new QName("http://soap.service.fantasy.game.soa.ls.com/", "AuthServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soap-service/AuthService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        AUTHSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AuthServiceImplService() {
        super(__getWsdlLocation(), AUTHSERVICEIMPLSERVICE_QNAME);
    }

    public AuthServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHSERVICEIMPLSERVICE_QNAME, features);
    }

    public AuthServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, AUTHSERVICEIMPLSERVICE_QNAME);
    }

    public AuthServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHSERVICEIMPLSERVICE_QNAME, features);
    }

    public AuthServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns AuthService
     */
    @WebEndpoint(name = "AuthServiceImplPort")
    public AuthService getAuthServiceImplPort() {
        return super.getPort(new QName("http://soap.service.fantasy.game.soa.ls.com/", "AuthServiceImplPort"), AuthService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns AuthService
     */
    @WebEndpoint(name = "AuthServiceImplPort")
    public AuthService getAuthServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.service.fantasy.game.soa.ls.com/", "AuthServiceImplPort"), AuthService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHSERVICEIMPLSERVICE_EXCEPTION != null) {
            throw AUTHSERVICEIMPLSERVICE_EXCEPTION;
        }
        return AUTHSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
