
package com.ls.soa.game.fantasy.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "AuthService", targetNamespace = "http://soap.service.fantasy.game.soa.ls.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface AuthService {


    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     * @throws UserNotFoundException_Exception
     * @throws IncorrectPasswordException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://soap.service.fantasy.game.soa.ls.com/", className = "com.ls.soa.game.fantasy.service.soap.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://soap.service.fantasy.game.soa.ls.com/", className = "com.ls.soa.game.fantasy.service.soap.LoginResponse")
    public String login(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1)
            throws IncorrectPasswordException_Exception, UserNotFoundException_Exception
    ;

}
