
package com.ls.soa.game.fantasy.service.soap;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CategoryDictionaryServiceImplService", targetNamespace = "http://soap.service.fantasy.game.soa.ls.com/", wsdlLocation = "http://localhost:8080/soap-service/CategoryDictionaryService?wsdl")
public class CategoryDictionaryServiceImplService
        extends Service {

    private final static URL CATEGORYDICTIONARYSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CATEGORYDICTIONARYSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CATEGORYDICTIONARYSERVICEIMPLSERVICE_QNAME = new QName("http://soap.service.fantasy.game.soa.ls.com/", "CategoryDictionaryServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soap-service/CategoryDictionaryService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CATEGORYDICTIONARYSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CATEGORYDICTIONARYSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CategoryDictionaryServiceImplService() {
        super(__getWsdlLocation(), CATEGORYDICTIONARYSERVICEIMPLSERVICE_QNAME);
    }

    public CategoryDictionaryServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CATEGORYDICTIONARYSERVICEIMPLSERVICE_QNAME, features);
    }

    public CategoryDictionaryServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CATEGORYDICTIONARYSERVICEIMPLSERVICE_QNAME);
    }

    public CategoryDictionaryServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CATEGORYDICTIONARYSERVICEIMPLSERVICE_QNAME, features);
    }

    public CategoryDictionaryServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CategoryDictionaryServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns CategoryDictionaryService
     */
    @WebEndpoint(name = "CategoryDictionaryServiceImplPort")
    public CategoryDictionaryService getCategoryDictionaryServiceImplPort() {
        return super.getPort(new QName("http://soap.service.fantasy.game.soa.ls.com/", "CategoryDictionaryServiceImplPort"), CategoryDictionaryService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CategoryDictionaryService
     */
    @WebEndpoint(name = "CategoryDictionaryServiceImplPort")
    public CategoryDictionaryService getCategoryDictionaryServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.service.fantasy.game.soa.ls.com/", "CategoryDictionaryServiceImplPort"), CategoryDictionaryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CATEGORYDICTIONARYSERVICEIMPLSERVICE_EXCEPTION != null) {
            throw CATEGORYDICTIONARYSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CATEGORYDICTIONARYSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
