
package com.ls.soa.game.fantasy.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "ElementService", targetNamespace = "http://soap.service.fantasy.game.soa.ls.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ElementService {


    /**
     * @param arg1
     * @param arg0
     * @return returns com.ls.soa.game.fantasy.service.soap.ElementDTO
     * @throws InsufficientPermissionsException_Exception
     * @throws InvalidTokenException_Exception
     * @throws CategoryDictionaryNotFoundException_Exception
     * @throws ElementNotFoundException_Exception
     * @throws UserNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://soap.service.fantasy.game.soa.ls.com/", className = "com.ls.soa.game.fantasy.service.soap.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://soap.service.fantasy.game.soa.ls.com/", className = "com.ls.soa.game.fantasy.service.soap.UpdateResponse")
    public ElementDTO update(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    ElementDTO arg1)
            throws CategoryDictionaryNotFoundException_Exception, ElementNotFoundException_Exception, InsufficientPermissionsException_Exception, InvalidTokenException_Exception, UserNotFoundException_Exception
    ;

}
