
package com.ls.soa.game.fantasy.service.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebFault(name = "InsufficientPermissionsException", targetNamespace = "http://soap.service.fantasy.game.soa.ls.com/")
public class InsufficientPermissionsException_Exception
        extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private InsufficientPermissionsException faultInfo;

    /**
     * @param faultInfo
     * @param message
     */
    public InsufficientPermissionsException_Exception(String message, InsufficientPermissionsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InsufficientPermissionsException_Exception(String message, InsufficientPermissionsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: com.ls.soa.game.fantasy.service.soap.InsufficientPermissionsException
     */
    public InsufficientPermissionsException getFaultInfo() {
        return faultInfo;
    }

}
